---
driver:
  name: ec2
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID']%>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY']%>
  aws_ssh_key_id: "<%= ENV['AWS_SSH_KEY_ID']%>"
  ssh_key: "<%= ENV['AWS_SSH_KEY']%>"
  require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      region: <%= ENV['EC2_REGION']%>
      availability_zone: <%= ENV['EC2_AVAILABILITY_ZONE']%>
      flavor_id: t2.micro
      image_id: ami-234ecc54
      username: ubuntu
      #elastic ip
  - name: amazon-linux
    driver:
      region: <%= ENV['EC2_REGION']%>
      availability_zone: <%= ENV['EC2_AVAILABILITY_ZONE']%>
      flavor_id: t2.micro
      image_id: ami-9d23aeea
      username: ec2-user

suites:
  - name: test
    #encrypted_data_bag_secret_key_path: "~/.chef/encrypted_data_bag_secret"
    data_bags_path: "../../data_bags"
    roles_path: "../../roles"
    run_list:
      - role[base]
      - recipe[learn_chef_httpd::default]
  - name: bastion
    run_list:
      - recipe[base::default]
      - recipe[bastion::default]
  - name: jenkins
    run_list:
      - recipe[base::default]
      - role[jenkins]
  - name: repo
    run_list:
      - recipe[base::default]
      - recipe[nexus::default]
      - recipe[sonar::default]