---
driver:
  name: ec2
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID']%>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY']%>
  aws_ssh_key_id: "<%= ENV['AWS_SSH_KEY_ID']%>"
  ssh_key: "<%= ENV['AWS_SSH_KEY']%>"
  require_chef_omnibus: true
  region: <%= ENV['EC2_REGION']%>
  availability_zone: <%= ENV['EC2_AVAILABILITY_ZONE']%>
  flavor_id: t2.micro

provisioner:
  name: chef_zero
  #encrypted_data_bag_secret_key_path: "~/.chef/encrypted_data_bag_secret"
  #data_bags_path: "data_bags"
  #roles_path: "roles"

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: ami-234ecc54
      username: ubuntu
      #elastic ip
  - name: amazon-linux
    driver:
      image_id: ami-9d23aeea
      username: ec2-user

suites:
  - name: base
    run_list:
      - role[base]
  - name: httpd
    run_list:
      - role[httpd]
  - name: jenkins
    run_list:
      - role[jenkins]